sudo: required

language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

services:
  - docker

# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: sh ./run_test_docker.sh
