version: '2.1'

services:
  lightweight-rest-tester:
    build:
      context: .
      dockerfile: ./images/Dockerfile.lightweight-rest-tester
    command: python -m unittest
    depends_on:
      - json-server
    links:
      - json-server

  json-server:
    build:
      context: .
      dockerfile: ./images/Dockerfile.json-server
