version: '2.1'

services:
  lightweight-rest-tester:
    build:
      context: .
      dockerfile: ./images/Dockerfile.lightweight-rest-tester
    command: sh run_test_coveralls.sh
    depends_on:
      json-server:
        condition: service_healthy
    links:
      - json-server

  json-server:
    build:
      context: .
      dockerfile: ./images/Dockerfile.json-server
